# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  convLibrary_config = debug
  main_config = debug

else ifeq ($(config),release)
  convLibrary_config = release
  main_config = release

else ifeq ($(config),releasesimd)
  convLibrary_config = releasesimd
  main_config = releasesimd

else ifeq ($(config),releasecsimd)
  convLibrary_config = releasecsimd
  main_config = releasecsimd

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := convLibrary main

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

convLibrary:
ifneq (,$(convLibrary_config))
	@echo "==== Building convLibrary ($(convLibrary_config)) ===="
	@${MAKE} --no-print-directory -C convLibrary -f Makefile config=$(convLibrary_config)
endif

main: convLibrary
ifneq (,$(main_config))
	@echo "==== Building main ($(main_config)) ===="
	@${MAKE} --no-print-directory -C main -f Makefile config=$(main_config)
endif

clean:
	@${MAKE} --no-print-directory -C convLibrary -f Makefile clean
	@${MAKE} --no-print-directory -C main -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  releasesimd"
	@echo "  releasecsimd"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   convLibrary"
	@echo "   main"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"